name: wheatley
description: 'Generate your test inputs with Weatley, a no frills library for property based testing.'
version: 0.1.1
repository: https://github.com/tjarvstrand/wheatley

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  characters: ^1.4.1
  meta: ^1.17.0

dev_dependencies:
  coverage: any
  lints: ^5.1.1
  test: ^1.26.3
