name: wheatley
description: 'A property based testing framework.'
version: 0.1.0

repository: https://github.com/tjarvtrand/wheatley

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  characters: ^1.4.1
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
