include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line: false
    - always_put_required_named_parameters_first: false
    - always_require_non_null_named_parameters: false # deprecated
    - always_specify_types: false
    - always_use_package_imports
    - annotate_redeclares
    - avoid_annotating_with_dynamic: false # May conflict with always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
#    - avoid_catches_without_on_clauses
#    - avoid_catching_errors
    - avoid_classes_with_only_static_members: false
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters: false
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values: false
    - avoid_returning_null: false # deprecated
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters: false
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_on_closure_parameters
    - avoid_unstable_final_fields
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
#    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - dangling_library_doc_comments: false
    - deprecated_consistency
    - deprecated_member_use_from_same_package: false
#    - diagnostic_describe_all_properties
    - directives_ordering
    - discarded_futures: false
    - do_not_use_environment
    - eol_at_end_of_file
    - flutter_style_todos: false
    - implicit_call_tearoffs
    - implicit_reopen
    - invalid_case_patterns
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_annotations
    - lines_longer_than_80_chars: false
    - literal_only_boolean_expressions
    - matching_super_parameters
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases: false
    - no_literal_bool_comparisons
    - no_runtimeType_toString
    - no_self_assignments
    - no_wildcard_variable_uses
    - noop_primitive_operations
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs: false
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_constructors_over_static_methods
    - prefer_double_quotes: false # Conflicts with prefer_single_quotes
    - prefer_expression_function_bodies: false
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters: false
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_relative_imports: false
    - prefer_single_quotes
#    - public_member_api_docs
    - require_trailing_commas: false
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
#    - type_annotate_public_apis
    - type_literal_in_constant_pattern
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_final: false
    - unnecessary_lambdas
    - unnecessary_library_directive
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_to_list_in_spreads
    - unreachable_from_main: false
    - unsafe_html
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools: false
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
#    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable

analyzer:
  exclude:
    - build/**
    - '**/**.freezed.dart'
    - 'lib/**.g.dart'
    - 'lib/**.graphql.dart'
    - 'lib/ui/djungo_custom_icons.dart'
    - '**/l10n/app_localizations*.dart'
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - no-equal-then-else

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
